/* Commitlint template for this repo. Adjust scopes as needed. */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'refactor',
        'chore',
        'docs',
        'test',
        'perf',
        'ci',
        'build',
        'style',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'backend',
        'manager',
        'aio',
        'desktop',
        'console',
        'mobile',
        'asr',
        'tts',
        'vad',
        'llm',
        'mcp',
        'storage',
        'config',
        'webassets',
        'docs',
      ],
    ],
    'type-case': [2, 'always', 'lower-case'],
    'scope-case': [2, 'always', 'lower-case'],
    'subject-max-length': [2, 'always', 72],
    'subject-empty': [2, 'never'],
    'type-empty': [2, 'never'],
  },
};
