version: "3.9"

services:
  aio-server:
    image: ghcr.io/xiaozhi-labs/xiaozhi-server:main
    ports:
      - "8002:8002"
      - "8007:8007"
      - "8009:8009"
    environment:
      XIAOZHI_ENABLE_SESSION_LOG: "false"
      XIAOZHI_DATABASE_DSN: "sqlite:///app/db/manager-server.db?_pragma=journal_mode(WAL)&_pragma=synchronous(NORMAL)"
    volumes:
      - ./db:/app/db
      - ./logs:/app/logs
    restart: unless-stopped
