// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLogs(arg1:string):Promise<string>;

export function GetServiceHealth():Promise<Record<string, any>>;

export function GetServiceStatus():Promise<Record<string, any>>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function OpenManagerWeb():Promise<string>;

export function RestartService(arg1:string):Promise<string>;

export function StartService(arg1:string):Promise<string>;

export function StopService(arg1:string):Promise<string>;
