// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: runner.proto

package runnerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	RunnerControl_Connect_FullMethodName = "/aider.runner.v1.RunnerControl/Connect"
)

// RunnerControlClient is the client API for RunnerControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RunnerControlClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (RunnerControl_ConnectClient, error)
}

type runnerControlClient struct {
	cc grpc.ClientConnInterface
}

func NewRunnerControlClient(cc grpc.ClientConnInterface) RunnerControlClient {
	return &runnerControlClient{cc}
}

func (c *runnerControlClient) Connect(ctx context.Context, opts ...grpc.CallOption) (RunnerControl_ConnectClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RunnerControl_ServiceDesc.Streams[0], RunnerControl_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &runnerControlConnectClient{ClientStream: stream}
	return x, nil
}

type RunnerControl_ConnectClient interface {
	Send(*RunnerMessage) error
	Recv() (*ServerMessage, error)
	grpc.ClientStream
}

type runnerControlConnectClient struct {
	grpc.ClientStream
}

func (x *runnerControlConnectClient) Send(m *RunnerMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *runnerControlConnectClient) Recv() (*ServerMessage, error) {
	m := new(ServerMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RunnerControlServer is the server API for RunnerControl service.
// All implementations must embed UnimplementedRunnerControlServer
// for forward compatibility
type RunnerControlServer interface {
	Connect(RunnerControl_ConnectServer) error
	mustEmbedUnimplementedRunnerControlServer()
}

// UnimplementedRunnerControlServer must be embedded to have forward compatible implementations.
type UnimplementedRunnerControlServer struct {
}

func (UnimplementedRunnerControlServer) Connect(RunnerControl_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedRunnerControlServer) mustEmbedUnimplementedRunnerControlServer() {}

// UnsafeRunnerControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RunnerControlServer will
// result in compilation errors.
type UnsafeRunnerControlServer interface {
	mustEmbedUnimplementedRunnerControlServer()
}

func RegisterRunnerControlServer(s grpc.ServiceRegistrar, srv RunnerControlServer) {
	s.RegisterService(&RunnerControl_ServiceDesc, srv)
}

func _RunnerControl_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RunnerControlServer).Connect(&runnerControlConnectServer{ServerStream: stream})
}

type RunnerControl_ConnectServer interface {
	Send(*ServerMessage) error
	Recv() (*RunnerMessage, error)
	grpc.ServerStream
}

type runnerControlConnectServer struct {
	grpc.ServerStream
}

func (x *runnerControlConnectServer) Send(m *ServerMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *runnerControlConnectServer) Recv() (*RunnerMessage, error) {
	m := new(RunnerMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RunnerControl_ServiceDesc is the grpc.ServiceDesc for RunnerControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RunnerControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aider.runner.v1.RunnerControl",
	HandlerType: (*RunnerControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _RunnerControl_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "runner.proto",
}
